// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlitestore

type Block struct {
	Number                  int64  `json:"number"`
	Hash                    []byte `json:"hash"`
	Parent                  []byte `json:"parent"`
	Block                   []byte `json:"block"`
	Receipts                []byte `json:"receipts"`
	CallTraces              []byte `json:"call_traces"`
	PrestateTraces          []byte `json:"prestate_traces"`
	Keccak256PreimageTraces []byte `json:"keccak256_preimage_traces"`
	StateAccessTraces       []byte `json:"state_access_traces"`
}

type TailBlock struct {
	ID     int64  `json:"id"`
	Number int64  `json:"number"`
	Hash   []byte `json:"hash"`
}
